#!/bin/sh

#  PassCydiaInstall
#  
#
#  Created by Dayton Hasty on 10/22/14.
#
clear
read -p "Make sure your iDevice and Mac are on the same network. Please enter the IP address of your device: " ipwhu
sleep 1
clear
echo "Creating Temporary Directory..."
cd ~
mkdir tmpcydia
cd tmpcydia
mkdir Cydia
cd Cydia
mkdir AutoInstall
cd AutoInstall
sleep 0.5
echo "Downloading Cydia Packages..."
wget 'http://apt.saurik.com/cydia/debs/cydia-lproj_1.1.12_iphoneos-arm.deb'
wget 'http://apt.saurik.com/cydia/debs/cydia_1.1.13_iphoneos-arm.deb'
clear
echo "Downloading Passcode Patch..."
sleep 2
cd ~
cd tmpcydia
wget 'https://raw.githubusercontent.com/dayt0n/Cydia8Install/master/move.sh'
clear
echo "Transfering Cydia Packages to Device..."
cd ~
sleep 0.5
sleep 2
ssh-keygen -R $ipwhu
sleep 0.5
clear
echo "Please enter your SSH password when prompted [default is alpine]"
scp -rp tmpcydia root@$ipwhu:/private/var/mobile/Media
sleep 1
clear
echo "Please enter your SSH password one last time."
ssh root@$ipwhu 'cd /private/var/mobile/Media/tmpcydia; mv Cydia /private/var/root/Media; cd /private/var/root/Media/Cydia/AutoInstall; sleep 0.5; dpkg -i cydia-lproj_1.1.12_iphoneos-arm.deb cydia_1.1.13_iphoneos-arm.deb; sleep 1; cd /private/var/mobile/Media/tmpcydia; mv move.sh /usr/libexec/cydia; cd /private/var/mobile/Media; rm -rf tmpcydia; cd /User/Library/Caches; rm *.csstore; sleep 1; cd /Applications; rm -rf pangu.app; reboot'
sleep 0.5
cd ~
rm -rf tmpcydia
clear
echo "Enjoy Cydia! Just remember not to turn on the passcode or else unspeakable things might happen..."
exit